apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleapp-deploy
spec:
  selector:
    matchLabels:
      app: exampleapp
  replicas: 2
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      containers:
      - name: exampleapp
        image: odeaver/exampleapp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: exampleapp-service
spec:
  selector:
    app: exampleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
