apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleapp-deploy
spec:
  selector:
    matchLabels:
      app: exampleapp
  replicas: 2
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      containers:
      - name: exampleapp
        image: odeaver/exampleapp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: exampleapp-service
spec:
  selector:
    app: exampleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - localhost.localdomain