apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleapp-deploy
spec:
  selector:
    matchLabels:
      app: exampleapp
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
      labels:
        app: exampleapp
    spec:
      containers:
      - name: exampleapp
        image: odeaver/exampleapp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: exampleapp-service
spec:
  selector:
    app: exampleapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 5000
