---

- hosts: all
  become: yes

  tasks:
  - name: Install python modules
    ansible.builtin.pip:
      name:
        - flask
        - pymongo

  - name: Install mongo
    ansible.builtin.yum:
      name: mongodb-org
      conf_file: /vagrant/mongodb-org-5.0.repo
  
  - name: Enable mongo
    ansible.builtin.systemd:
      name: mongod
      enabled: yes
  
  - name: Copy in app service
    ansible.builtin.copy:
      src: /vagrant/app.service
      dest: /etc/systemd/system
  
  - name: Enable app
    ansible.builtin.systemd:
      name: app
      enabled: yes
      daemon-reload: yes

    
