---

- hosts: all
  become: yes

  tasks:
  - name: Install mongo
    ansible.builtin.yum:
      name: mongodb-org
      conf_file: /vagrant/mongodb-org-5.0.repo
  
  - name: Enable mongo
    ansible.builtin.systemd:
      name: mongod
      enabled: yes

  - name: Add docker repo
    ansible.builtin.yum_repository:
      name: docker
      description: Docker Repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker
    ansible.builtin.yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  
  - name: Start docker
    ansible.builtin.systemd:
      name: docker
      state: started

  - name: Copy in app service
    ansible.builtin.copy:
      source: /vagrant/app.service
      dest: /etc/systemd/system

  - name: Start app service
    ansible.builtin.systemd:
      name: app
      enabled: yes
      state: started
