- name: Add bitnami repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install mongo chart
  kubernetes.core.helm:
    name: mongo
    namespace: default
    chart_ref: bitnami/mongodb
    values:
      persistence:
        size: 1Gi
      auth:
        enabled: false
      architecture: "replicaset"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9216"