- name: Turn off swapping
  block:

    - name: Get rid of swap device
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: "swapfile"
        state: absent

    - name: Turn off swap
      ansible.builtin.shell: swapoff -a

    - name: Delete swapfile
      ansible.builtin.file:
        path: /swapfile
        state: absent

- name: Turn on br_netfilter
  block:

    - name: Load br_netfilter module on boot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf
        create: yes
        line: br_netfilter

    - name: Load br_netfilter
      ansible.builtin.shell: modprobe br_netfilter

    - name: Enable bridge traffic viewing
      ansible.builtin.blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Refresh sysctl variables
      ansible.builtin.shell: sysctl --system

- name: Turn off selinux
  ansible.posix.selinux:
    state: disabled

- name: Install kubernetes software
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  block:

    - name: Add kubernetes repo
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Install rpms
      ansible.builtin.yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
    
    - name: Enable kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Initialize k8s cluster
      ansible.builtin.shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      # not idempotent
      ignore_errors: yes

    - name: Allow pods to run on control node
      ansible.builtin.shell: kubectl taint nodes --all node-role.kubernetes.io/master-
      # not idempotent
      ignore_errors: yes

    - name: Install flannel network plugin
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    
    - name: Wait for flannel install
      ansible.builtin.wait_for:
        path: /run/flannel/subnet.env