- name: Add prometheus chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Add kube-state-metrics repo
  kubernetes.core.helm_repository:
    name: kube-state-metrics
    repo_url: https://kubernetes.github.io/kube-state-metrics

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: default
    values:
      prometheusSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
          selector: {}
      grafana:
        service:
          externalIPs:
            - "192.168.33.11"
        grafana.ini:
          auth.anonymous:
            enabled: true

- name: Add service monitors
  ansible.builtin.shell: kubectl apply -f /vagrant/serviceMonitors.yaml        
